# Generated by Django 6.0.6 on 2026-06-06 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('amazon_url', 'Amazon URL'), ('product_photos', 'Product Photos')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_analysis', 'Ready for Analysis'), ('pending_analysis', 'Pending Analysis'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('amazon_url', models.URLField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('main_benefit', models.TextField(blank=True)),
                ('current_title', models.CharField(blank=True, max_length=500)),
                ('bullet_points', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('backend_keywords', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('review_count', models.CharField(blank=True, max_length=20)),
                ('target_audience', models.TextField(blank=True)),
                ('seller_goal', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='audit_images/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='audits.audit')),
            ],
        ),
    ]
