# Generated by Django 6.0.6 on 2026-06-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('score_label', models.CharField(blank=True, max_length=255)),
                ('executive_summary', models.TextField()),
                ('conversion_diagnosis', models.JSONField(default=dict)),
                ('weak_points', models.JSONField(default=list)),
                ('title_analysis', models.JSONField(default=dict)),
                ('improved_title', models.TextField()),
                ('bullet_improvements', models.JSONField(default=list)),
                ('improved_bullets', models.JSONField(default=list)),
                ('description_analysis', models.JSONField(default=dict)),
                ('improved_description', models.TextField()),
                ('keyword_opportunities', models.JSONField(default=list)),
                ('review_insights', models.JSONField(default=list)),
                ('buyer_objections', models.JSONField(default=list)),
                ('a_plus_content_ideas', models.JSONField(default=list)),
                ('image_pack_plan', models.JSONField(default=list)),
                ('priority_checklist', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='audits.audit')),
            ],
        ),
    ]
