# Generated by Django 6.0.6 on 2026-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='a_plus_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='about_this_item',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='brand_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='buyer_complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='product_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='product_images_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='product_specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='reviews_qna',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='size_guide',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='variations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='videos_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='concise_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='report_version',
            field=models.CharField(default='v1', max_length=10),
        ),
    ]
