# Generated by Django 6.0.6 on 2026-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='background_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='brief',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='product_visual_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='style_direction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='text_intensity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
