# Generated by Django 6.0.6 on 2026-06-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagegeneration_background_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='generation_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='product_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='reference_image_url',
            field=models.TextField(blank=True),
        ),
    ]
