PLANS = {
    'free_trial': {
        'key': 'free_trial',
        'name': 'Free Trial',
        'price_display': '$0',
        'amount_cents': 0,
        'mode': 'free',
        'audit_credits': 1,
        'full_upgrade_credits': 0,
        'image_generation_credits': 0,
        'features': [
            '1 limited audit',
            'No full upgrades',
        ],
    },
    'full_upgrade': {
        'key': 'full_upgrade',
        'name': 'Full Listing Upgrade',
        'price_display': '$29',
        'amount_cents': 2900,
        'mode': 'payment',
        'audit_credits': 0,
        'full_upgrade_credits': 1,
        'image_generation_credits': 0,
        'features': [
            '1 full listing upgrade',
            'One-time purchase',
        ],
    },
    'launch': {
        'key': 'launch',
        'name': 'Launch',
        'price_display': '$19/mo',
        'amount_cents': 1900,
        'mode': 'subscription',
        'audit_credits': 3,
        'full_upgrade_credits': 1,
        'image_generation_credits': 0,
        'features': [
            '3 audits/month',
            '1 full upgrade/month',
        ],
    },
    'pro': {
        'key': 'pro',
        'name': 'Pro',
        'price_display': '$39/mo',
        'amount_cents': 3900,
        'mode': 'subscription',
        'audit_credits': 7,
        'full_upgrade_credits': 3,
        'image_generation_credits': 0,
        'features': [
            '7 audits/month',
            '3 full upgrades/month',
        ],
    },
    'growth': {
        'key': 'growth',
        'name': 'Growth',
        'price_display': '$59/mo',
        'amount_cents': 5900,
        'mode': 'subscription',
        'audit_credits': 10,
        'full_upgrade_credits': 5,
        'image_generation_credits': 0,
        'features': [
            '10 audits/month',
            '5 full upgrades/month',
        ],
    },
    'agency': {
        'key': 'agency',
        'name': 'Agency',
        'price_display': '$149/mo',
        'amount_cents': 14900,
        'mode': 'subscription',
        'audit_credits': 25,
        'full_upgrade_credits': 15,
        'image_generation_credits': 0,
        'features': [
            '25 audits/month',
            '15 full upgrades/month',
        ],
    },
    'extra_upgrade': {
        'key': 'extra_upgrade',
        'name': 'Extra Full Upgrade',
        'price_display': '$19',
        'amount_cents': 1900,
        'mode': 'payment',
        'audit_credits': 0,
        'full_upgrade_credits': 1,
        'image_generation_credits': 0,
        'features': [
            '1 additional full upgrade',
        ],
    },
    'extra_audit_pack': {
        'key': 'extra_audit_pack',
        'name': 'Extra Audit Pack',
        'price_display': '$9',
        'amount_cents': 900,
        'mode': 'payment',
        'audit_credits': 1,
        'full_upgrade_credits': 0,
        'image_generation_credits': 0,
        'features': [
            '1 additional audit',
        ],
    },
}

PLAN_KEYS = list(PLANS.keys())
