PLANS = {
    'free_trial': {
        'key': 'free_trial',
        'name': 'Free Trial',
        'price_display': '$0',
        'amount_cents': 0,
        'mode': 'free',
        'audit_credits': 1,
        'full_upgrade_credits': 0,
        'image_generation_credits': 0,
        'features': [
            '1 limited audit',
            'Basic listing diagnosis',
            'Preview recommendations',
        ],
    },
    'launch': {
        'key': 'launch',
        'name': 'Launch',
        'price_display': '$9/mo',
        'amount_cents': 900,
        'mode': 'subscription',
        'audit_credits': 5,
        'full_upgrade_credits': 1,
        'image_generation_credits': 10,
        'features': [
            '5 audits/month',
            '1 full upgrade/month',
            '10 image generations/month',
        ],
    },
    'pro': {
        'key': 'pro',
        'name': 'Pro',
        'price_display': '$19/mo',
        'amount_cents': 1900,
        'mode': 'subscription',
        'audit_credits': 12,
        'full_upgrade_credits': 3,
        'image_generation_credits': 35,
        'features': [
            '12 audits/month',
            '3 full upgrades/month',
            '35 image generations/month',
        ],
    },
    'growth': {
        'key': 'growth',
        'name': 'Growth',
        'price_display': '$29/mo',
        'amount_cents': 2900,
        'mode': 'subscription',
        'audit_credits': 15,
        'full_upgrade_credits': 5,
        'image_generation_credits': 60,
        'features': [
            '15 audits/month',
            '5 full upgrades/month',
            '60 image generations/month',
        ],
    },
    'agency': {
        'key': 'agency',
        'name': 'Agency',
        'price_display': '$59/mo',
        'amount_cents': 5900,
        'mode': 'subscription',
        'audit_credits': 30,
        'full_upgrade_credits': 15,
        'image_generation_credits': 150,
        'features': [
            '30 audits/month',
            '15 full upgrades/month',
            '150 image generations/month',
        ],
    },
}

PLAN_KEYS = list(PLANS.keys())
